dist: trusty

sudo: false

cache:
  directories:
  - $HOME/.bin

language: go

go:
  - 1.8

before_install:
  - mkdir -p $HOME/.bin
  - if [ ! -f $HOME/.bin/glide ]; then curl -Ls https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz | tar --strip-components=1 -x -z -C $HOME/.bin linux-amd64/glide; chmod +x $HOME/.bin/glide; fi
  - git describe --exact-match --tags $(git log -n1 --pretty='%h') > .version || git rev-parse HEAD > .version

install: PATH=$PATH:$HOME/.bin make clean all

script: PATH=$PATH:$HOME/.bin make test
